name: infra-compose
services:
  infra-db:
    image: postgres:15.4
    command: -p 5432 -c idle_session_timeout=1805000
    environment:
      POSTGRES_USER: devteller
      POSTGRES_PASSWORD: devteller123!
    ports:
      - "5432:5432"